name: Manual run

on:
  issues:
    types: [opened]
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'PRINT')
    steps:
    - name: Accept the task
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}  
        body: |
          Will print contents of `${{github.event.issue.body}}` .
    - uses: actions/checkout@v2
    - name: Run tests
      id: run_bench
      run: |
        cat ${{github.event.issue.body}} | tee results.txt
        REPORT="$(cat results.txt)"
        REPORT="${REPORT//'%'/'%25'}"
        REPORT="${REPORT//$'\n'/'%0A'}"
        REPORT="${REPORT//$'\r'/'%0D'}"
        echo "::set-output name=results::$REPORT"
    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          Here you go!
          ```
          ${{ steps.run_bench.outputs.results }}
          ```
