name: Manual run

on:
  push:
    branches:
      - master
      
env:
  ENV_VARIABLE: 42

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'PRINT')
    steps:
    - name: print a variable
      run: echo $ENV_VARIABLE
