name: Manual run

on:
  push:
    branches:
      - master
      
env:
  ENV_VARIABLE: 42

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print a variable
      timeout-minutes: ${{ env.ENV_VARIABLE }}
      run: echo $ENV_VARIABLE
