name: Manual run

on:
  push:
    branches:
      - master
      
env:
  ENV_VARIABLE: 42
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print a variable
      timeout-minutes: ${{ fromJSON(env.ENV_VARIABLE) }}
      run: echo $ENV_VARIABLE
    - name: print a variable
      timeout-minutes: 42
      run: echo $ENV_VARIABLE
